dev: update cicd (#12)

diff --git a/bin/dev-lib-bashlib64 b/bin/dev-lib-bashlib64
--- a/bin/dev-lib-bashlib64
+++ b/bin/dev-lib-bashlib64
@@ -1,17 +1,49 @@
 #!/usr/bin/env bash
+#######################################
+# Dev / Lib / Bashlib64 / Download
 #
-# Update dev-time external tool: BashLib64
+# * Version: 4.1.0
 #
-# * Template: 2.1.0
+#######################################
+# Copyright [2023] [serdigital64@gmail.com]
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#######################################
+
+#
+# Imports
 #
 
-# shellcheck source=SCRIPTDIR/dev-set
-source ./bin/dev-set || exit 1
+# shellcheck source=bin/dev-set
+source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
 
-[[ -z "$DEV_CICD_INSTALLER64_BIN" ]] &&
-  echo 'error: Installer64 not found. Use the dev-lib-instaler64 script to deploy it)' &&
-  exit 1
+#
+# Globals
+#
 
-echo 'Deploy application'
-export INST64_BASHLIB64_TARGET="$DEV_CICD_BASHLIB64"
-"${DEV_CICD_BASHLIB64_INSTALLER}"
+# CICD / Debug flag for bin/ scripts. Set to YES to enable
+export DEV_CICD_DEBUG="${DEV_CICD_DEBUG:-}"
+# Lib / BashLib64 / Target
+export DEV_LIB_BASHLIB64_TARGET="${DEV_LIB_BASHLIB64_TARGET:-${DEV_PATH_LIB}/bl64}"
+# Lib / BashLib64 / Installer64 parameters
+export INST64_BASHLIB64_TARGET="$DEV_LIB_BASHLIB64_TARGET"
+
+#
+# Main
+#
+
+[[ -n "$DEV_CICD_DEBUG" ]] && set -x
+[[ ! -d "$DEV_LIB_INSTALLER64_TARGET" ]] && dev_set_error 'Installer64 not found, please run ./bin/dev-lib-installer64 and try again' && exit 1
+
+[[ -d "$DEV_LIB_BASHLIB64_TARGET" ]] && rm -Rf "$DEV_LIB_BASHLIB64_TARGET"
+"${DEV_LIB_INSTALLER64_TARGET}/install-bashlib64"
diff --git a/bin/dev-lib-installer64 b/bin/dev-lib-installer64
--- a/bin/dev-lib-installer64
+++ b/bin/dev-lib-installer64
@@ -1,16 +1,55 @@
 #!/usr/bin/env bash
+#######################################
+# Dev / Lib / Installer64 / Download
 #
-# Update dev-time external tool: Installer64
+# * Version: 3.1.0
 #
-# * Template: 1.4.0
+#######################################
+# Copyright [2023] [serdigital64@gmail.com]
+#
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#######################################
+
+#
+# Imports
 #
 
-# shellcheck source=SCRIPTDIR/dev-set
-source ./bin/dev-set || exit 1
+# shellcheck source=bin/dev-set
+source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
+# shellcheck source-path=bin
+source ./bin/dev-env-installer64 || exit 1
 
-echo 'Deploy installer: Installer64'
-export INST64_INSTALLER64_TARGET="$DEV_CICD_INSTALLER64_TARGET"
-cd "$DEV_LIB" &&
-  curl -LO "$DEV_CICD_INSTALLER64_URL" &&
-  chmod 755 "$DEV_CICD_INSTALLER64_BIN" &&
-  "$DEV_CICD_INSTALLER64_BIN"
+#
+# Globals
+#
+
+# CICD / Debug flag for bin/ scripts. Set to YES to enable
+export DEV_CICD_DEBUG="${DEV_CICD_DEBUG:-}"
+# Lib / Installer64 / Source
+export DEV_LIB_INSTALLER64_URL='https://raw.githubusercontent.com/automation64/installer64/main/src/install-installer64'
+# Lib / Installer64 / Installer64 parameters
+export INST64_INSTALLER64_TARGET="$DEV_LIB_INSTALLER64_TARGET"
+# Lib / BashLib64 / Installer64 parameters
+export INST64_BASHLIB64_TARGET="$DEV_LIB_BASHLIB64_TARGET"
+
+#
+# Main
+#
+
+[[ -n "$DEV_CICD_DEBUG" ]] && set -x
+
+[[ -d "$DEV_LIB_INSTALLER64_TARGET" ]] && rm -Rf "$DEV_LIB_INSTALLER64_TARGET"
+cd "$DEV_PATH_LIB" &&
+  curl -LO "$DEV_LIB_INSTALLER64_URL" &&
+  bash './install-installer64' &&
+  rm -f 'install-installer64'
diff --git a/bin/dev-set b/bin/dev-set
--- a/bin/dev-set
+++ b/bin/dev-set
@@ -1,9 +1,9 @@
 #!/usr/bin/env bash
 #######################################
-# Set development environment variables
+# Dev / Set development environment variables
 #
 # * Source this script from the project's root directory
-# * Template Version: 7.0.0
+# * Version: 7.3.1
 #
 #######################################
 # Copyright [2023] [serdigital64@gmail.com]
@@ -25,7 +25,14 @@
 # Globals
 #
 
-export DEV_SET_VERBOSE="${DEV_SET_VERBOSE:-verbose}"
+# CICD / Debug flag for bin/ scripts. Set to YES to enable
+export DEV_CICD_DEBUG="${DEV_CICD_DEBUG:-}"
+# Dev / Set / Increase verbosity? Set to YES to increase
+export DEV_SET_VERBOSE="${DEV_SET_VERBOSE:-}"
+# Dev / Set / Resource names
+export DEV_BASE_LOCAL='.local'
+export DEV_BASE_SECRETS='.secrets'
+export DEV_BASE_ENV='.env'
 
 #
 # Functions
@@ -33,87 +40,86 @@ export DEV_SET_VERBOSE="${DEV_SET_VERBOSE:-verbose}"
 
 function dev_set_error() {
   local msg="$1"
-  echo "dev-set:Error: ${msg}"
+  echo "dev:Error: ${msg}" 2>&1
   return 0
 }
 
 function dev_set_message() {
   local msg="$1"
-  [[ "$DEV_SET_VERBOSE" == 'verbose' ]] && echo "dev-set: ${msg}"
+  [[ -n "$DEV_SET_VERBOSE" ]] && echo "dev: ${msg}"
   return 0
 }
 
 function dev_set_load_local() {
-  local dot_local='.local'
-  local dot_secrets='.secrets'
+  dev_set_message "Task: load local environment variables ($(pwd)/${DEV_BASE_LOCAL})"
+  export DEV_PATH_ROOT="${DEV_PATH_ROOT:-$(pwd)}"
 
-  dev_set_message "Load local environment variables ($(pwd)/${dot_local})"
-  # shellcheck source=SCRIPTDIR/../.local
-  source "$dot_local" ||
+  # shellcheck source=./.local
+  source "$DEV_BASE_LOCAL" ||
     {
-      dev_set_error "unable to source file (${dot_local})"
+      dev_set_error "unable to source file (${DEV_BASE_LOCAL})"
       return 1
     }
-  dot_secrets="${DEV_ROOT}/${dot_secrets}"
-  if [[ -f "$dot_secrets" ]]; then
-    dev_set_message "Load local secrets (${dot_secrets})"
-    # shellcheck source=SCRIPTDIR/../.secrets
-    source "${dot_secrets}" ||
+  DEV_BASE_SECRETS="${DEV_PATH_ROOT}/${DEV_BASE_SECRETS}"
+  if [[ -f "$DEV_BASE_SECRETS" ]]; then
+    dev_set_message "Task: load local secrets (${DEV_BASE_SECRETS})"
+    # shellcheck source=./.secrets
+    source "${DEV_BASE_SECRETS}" ||
       {
-        dev_set_error "unable to source file (${dot_secrets})"
+        dev_set_error "unable to source file (${DEV_BASE_SECRETS})"
         return 1
       }
   fi
 }
 
 function dev_set_load_gitlab() {
-  dev_set_message "GitLab detected, setting project root (${CI_PROJECT_DIR})"
+  # shellcheck disable=SC2154
+  dev_set_message "Info: GitLab detected, setting project root (${CI_PROJECT_DIR})"
   # shellcheck disable=SC2155
-  export DEV_ROOT="$CI_PROJECT_DIR"
+  export DEV_PATH_ROOT="$CI_PROJECT_DIR"
 }
 
 function dev_set_load_github() {
-  local dot_local='.local-github'
+  local DEV_BASE_LOCAL='.local-github'
 
-  dev_set_message "GitHub detected, setting project root (${GITHUB_WORKSPACE})"
+  dev_set_message "Info: GitHub detected, setting project root (${GITHUB_WORKSPACE})"
   # shellcheck disable=SC2155
-  export DEV_ROOT="$GITHUB_WORKSPACE"
+  export DEV_PATH_ROOT="$GITHUB_WORKSPACE"
 
-  dot_local="${DEV_ROOT}/${dot_local}"
-  if [[ -f "$dot_local" ]]; then
-    dev_set_message "Load local github automatic environment variables (${dot_local})"
-    # shellcheck source=SCRIPTDIR/../.local-github
-    source "${dot_local}" ||
+  DEV_BASE_LOCAL="${DEV_PATH_ROOT}/${DEV_BASE_LOCAL}"
+  if [[ -f "$DEV_BASE_LOCAL" ]]; then
+    dev_set_message "Task: Load local github automatic environment variables (${DEV_BASE_LOCAL})"
+    # shellcheck disable=SC1090
+    source "${DEV_BASE_LOCAL}" ||
       {
-        dev_set_error "unable to source file (${dot_local})"
+        dev_set_error "unable to source file (${DEV_BASE_LOCAL})"
         return 1
       }
   fi
 }
 
 function dev_set_load_testmansh() {
-  dev_set_message "Testmansh container detected, setting project root (${TESTMANSH_PROJECT_ROOT})"
-  export DEV_ROOT="$TESTMANSH_PROJECT_ROOT"
+  dev_set_message "Info: testmansh container detected, setting project root (${TESTMANSH_PROJECT_ROOT})"
+  export DEV_PATH_ROOT="$TESTMANSH_PROJECT_ROOT"
 }
 
 function dev_set_load_exported() {
-  dev_set_message 'Read DEV_ROOT variable from exported shell environment'
+  dev_set_message 'Info: read DEV_PATH_ROOT variable from exported shell environment'
 }
 
 function dev_set_check_root() {
-  if [[ -z "$DEV_ROOT" ]]; then
-    dev_set_error 'unable to identify current repository location. Check that the variable DEV_ROOT is correctly set' &&
+  if [[ -z "$DEV_PATH_ROOT" ]]; then
+    dev_set_error 'unable to identify current repository location. Check that the variable DEV_PATH_ROOT is correctly set' &&
       return 1
   fi
 }
 
 function dev_set_load_env() {
-  local dot_env="${DEV_ROOT}/.env"
-  dev_set_message "Load project environment variables (${dot_env})"
-  # shellcheck source=SCRIPTDIR/../.env
-  source "$dot_env" ||
+  dev_set_message "Task: load project environment variables (${DEV_BASE_ENV})"
+  # shellcheck source=./.env
+  source "$DEV_BASE_ENV" ||
     {
-      dev_set_error "unable to read environment variables (${dot_env})"
+      dev_set_error "unable to read environment variables (${DEV_BASE_ENV})"
       return 1
     }
 }
@@ -122,8 +128,11 @@ function dev_set_load_env() {
 # Main
 #
 
+[[ ! -f '.env' ]] && dev_set_error "script must be run from the project's root path" && return 1
+[[ -n "$DEV_CICD_DEBUG" ]] && set -x
+
 # shellcheck disable=SC2154
-if [[ -f ./.local ]]; then
+if [[ -f "$DEV_BASE_LOCAL" ]]; then
   dev_set_load_local
 elif [[ -n "$GITHUB_WORKSPACE" ]]; then
   dev_set_load_github
@@ -137,6 +146,7 @@ fi
 
 # shellcheck disable=SC2015
 dev_set_check_root &&
-  dev_set_load_env &&
-  dev_set_message 'Dev environment variables loading completed OK' ||
-  { dev_set_error 'Failed to load Dev environment variables'; return 1; }
+  dev_set_load_env ||
+  { dev_set_error 'failed to load Dev environment variables'; return 1; }
+[[ -n "$DEV_CICD_DEBUG" ]] && set +x
+:
diff --git a/bin/dev-test-bash b/bin/dev-test-bash
--- a/bin/dev-test-bash
+++ b/bin/dev-test-bash
@@ -1,40 +1,115 @@
 #!/usr/bin/env bash
+#######################################
+# Dev / Test / Bash / Simple test runner
 #
-# Run test-cases
+# * Run tests in test/bash using containers
+# * Version: 1.0.0
 #
-# * Test cases are done using bats-core
-# * TestManSH is used to manage test environment
-# * Tests are located in the default path "test/batscore"
-# * Template: 2.0.1
+#######################################
+# Copyright [2023] [serdigital64@gmail.com]
 #
+# Licensed under the Apache License, Version 2.0 (the "License");
+# you may not use this file except in compliance with the License.
+# You may obtain a copy of the License at
+#
+#     http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+#######################################
+
+#
+# Globals
+#
+
+# Dev / Test / Base / Flag for marking container environment
+export _DEV_TEST_BASH_CONTAINER_ENVIRONMENT='OFF'
 
 #
 # Imports
 #
 
-# shellcheck source=SCRIPTDIR/dev-set
-source ./bin/dev-set || exit 1
-# shellcheck source-path=SCRIPTDIR/../lib/bl64
-source "${DEV_CICD_BASHLIB64}/bashlib64-core.bash" || exit 1
+# shellcheck source=bin/dev-set
+source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
+# shellcheck source-path=bin
+source ./bin/dev-env-bash || exit 1
+# shellcheck source-path=lib/bl64
+source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-fmt.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-txt.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-fs.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-cnt.bash" &&
+  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-core.bash" || exit 1
+
+#
+# Functions
+#
+
+function dev_test_run() {
+  bl64_dbg_app_show_function "$@"
+  local container_path="$1"
+  local test_file="$2"
+
+  bl64_msg_show_phase "run test target: ${test_file}"
+  # shellcheck disable=SC2086
+  bl64_cnt_run \
+    $BL64_CNT_SET_RM \
+    $BL64_CNT_SET_TTY \
+    --env=_DEV_TEST_BASH_CONTAINER_ENVIRONMENT='ON' \
+    --workdir="$DEV_ENV_BASH_CONTAINER_PATH_ROOT" \
+    --mount "type=bind,source=${DEV_PATH_SRC},target=${DEV_ENV_BASH_CONTAINER_PATH_SRC},readonly" \
+    --mount "type=bind,source=${DEV_PATH_ROOT},target=${DEV_ENV_BASH_CONTAINER_PATH_ROOT},readonly" \
+    --mount "type=bind,source=${DEV_PATH_TEST},target=${DEV_ENV_BASH_CONTAINER_PATH_TEST},readonly" \
+    --entrypoint="${DEV_ENV_BASH_CONTAINER_PATH_ROOT}/${test_file}" \
+    "${DEV_ENV_BASH_REGISTRY}/${container_path}" ||
+    return $?
+}
+
+function dev_test_bash() {
+  bl64_dbg_app_show_function "$@"
+  local container="$1"
+  shift
+  local target="$*"
+  local current=''
+  local tests=''
+
+  bl64_dbg_app_show_comments 'define target tests'
+  if [[ -z "$target" ]]; then
+    target="$DEV_TEST_BASH_CASES"
+  fi
+  if [[ -d "$target" ]]; then
+    bl64_dbg_app_show_comments "look for tests (${target})"
+    tests="$(bl64_fs_find_files "$target")" ||
+      return $?
+  else
+    tests="$target"
+  fi
+  bl64_msg_show_info "test container: ${container}"
+  for current in $tests; do
+    dev_test_run "${container}" "$current" ||
+      return $?
+  done
+}
+
+function dev_test_initialize() {
+  bl64_dbg_app_show_function
+  bl64_cnt_setup
+}
 
 #
 # Main
 #
 
-declare -u target="${1:-RHEL}"
-declare container_var=''
-declare container_list=''
+declare dev_test_container="${1:-${DEV_TEST_BASH_CONTAINER}}"
+shift
+declare dev_test_target="${*:-}"
 
 [[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable
 
-bl64_check_export 'DEV_NAME_TEST' &&
-  bl64_check_export 'DEV_CICD_TESTMANSH' ||
-  exit $?
-
 bl64_msg_all_enable_verbose
-bl64_msg_show_batch_start 'test-bash'
-container_var="DEV_CICD_TEST_CONTAINER_CLI_${target}"
-bl64_check_export "$container_var" || exit $?
-eval container_list="\$$container_var"
-"$DEV_CICD_TESTMANSH" -b -o -e "$container_list" -c "${DEV_NAME_TEST}/batscore/cli"
-bl64_msg_show_batch_finish $? 'test-bash'
+bl64_msg_show_batch_start 'dev-test-bash'
+dev_test_initialize &&
+  dev_test_bash "$dev_test_container" "$dev_test_target"
+bl64_msg_show_batch_finish $? 'dev-test-bash'
