dev: move to shared lib

diff --git a/bin/devap-build b/bin/devap-build
--- a/bin/devap-build
+++ b/bin/devap-build
@@ -8,15 +8,14 @@
 # Version: 1.2.0
 #######################################
 
-[[ -d "$DEVAP_BIN" ]] || {
-  echo "Error: dev environment not set"
+# shellcheck source=SCRIPTDIR/devap-set
+source './bin/devap-set' || {
+  echo 'unable to load dev env'
   exit 1
 }
 
-# shellcheck disable=SC2034
-BL64_LIB_STRICT='0'
-# shellcheck disable=SC1091
-source "${DEVAP_BIN}/bashlib64.bash" || exit 1
+# shellcheck source-path=SCRIPTDIR/../lib disable=SC2154
+source "$DEVAP_BASHLIB64" || exit 1
 
 function devap_build_test() {
 
@@ -231,7 +230,7 @@ while getopts ':ritpuc:h' devap_build_option; do
     ;;
   c) devap_build_collection="$OPTARG" ;;
   h) devap_build_help && exit ;;
-  \?) devap_build_help && exit 1 ;;
+  *) devap_build_help && exit 1 ;;
   esac
 done
 [[ -z "$devap_build_command" ]] && devap_build_help && exit 1
@@ -259,6 +258,7 @@ bl64_msg_show_batch_start "$devap_build_command_tag"
 case "$devap_build_command" in
 'devap_build_test' | 'devap_build_prod' | 'devap_build_publish' | 'devap_build_refresh') "$devap_build_command" "$devap_build_collection" ;;
 'devap_build_installer') "$devap_build_command" ;;
+*) bl64_check_show_undefined "$devap_build_command" ;;
 esac
 devap_build_status=$?
 
diff --git a/bin/devap-test b/bin/devap-test
--- a/bin/devap-test
+++ b/bin/devap-test
@@ -8,15 +8,14 @@
 # Version: 1.2.0
 #######################################
 
-[[ -d "$DEVAP_BIN" ]] || {
-  echo "Error: dev environment not set"
+# shellcheck source=SCRIPTDIR/devap-set
+source './bin/devap-set' || {
+  echo 'unable to load dev env'
   exit 1
 }
 
-# shellcheck disable=SC2034
-BL64_LIB_STRICT='0'
-# shellcheck disable=SC1091
-source "${DEVAP_BIN}/bashlib64.bash"
+# shellcheck source-path=SCRIPTDIR/../lib disable=SC2154
+source "$DEVAP_BASHLIB64" || exit 1
 
 function devap_test_prepare_environment() {
   # Tune kernel for multiple containers
@@ -269,7 +268,7 @@ while getopts ':rvgldqc:e:i:n:xh' devap_test_option; do
   i) devap_test_target="$OPTARG" ;;
   n) devap_test_group="$OPTARG" ;;
   h) devap_test_help && exit ;;
-  \?) devap_test_help && exit 1 ;;
+  *) devap_test_help && exit 1 ;;
   esac
 done
 [[ -z "$devap_test_command" ]] && devap_test_help && exit 1
@@ -304,16 +303,10 @@ case "$devap_test_command" in
     "$devap_test_target" \
     "$devap_test_group"
   ;;
-'devap_test_role_login')
-  "$devap_test_command" \
-    "$devap_test_collection" "$devap_test_role" "$devap_test_target" "$devap_test_group"
-  ;;
-'devap_test_role_list')
-  "$devap_test_command" "$devap_test_collection" "$devap_test_role"
-  ;;
-'devap_test_reset')
-  "$devap_test_command"
-  ;;
+'devap_test_role_login') "$devap_test_command" "$devap_test_collection" "$devap_test_role" "$devap_test_target" "$devap_test_group" ;;
+'devap_test_role_list') "$devap_test_command" "$devap_test_collection" "$devap_test_role" ;;
+'devap_test_reset') "$devap_test_command" ;;
+*) bl64_check_show_undefined "$devap_test_command" ;;
 esac
 devap_test_status=$?
 
