dev: add collection doc refresh

diff --git a/bin/devap-build b/bin/devap-build
--- a/bin/devap-build
+++ b/bin/devap-build
@@ -8,7 +8,10 @@
 # Version: 1.1.0
 #######################################
 
-[[ -d "$DEVAP_BIN" ]] || { echo "Error: dev environment not set"; exit 1; }
+[[ -d "$DEVAP_BIN" ]] || {
+  echo "Error: dev environment not set"
+  exit 1
+}
 
 # shellcheck disable=SC2034
 BL64_LIB_STRICT='0'
@@ -40,6 +43,26 @@ function devap_build_test() {
   bl64_msg_show_task 'remove version tag from package file names'
   for collection in $DEVAP_NAMESPACE-*-*.tar.gz; do
     $BL64_OS_ALIAS_MV "$collection" "${collection%-*}.tar.gz"
+  done
+
+}
+
+function devap_build_refresh() {
+
+  local target="$1"
+  local collection=''
+
+  if [[ -z "$target" ]]; then
+    target="$(
+      cd "$DEVAP_COLLECTIONS" || return 1
+      echo *
+    )"
+  fi
+
+  for collection in $target; do
+    bl64_msg_show_task 'refreshing collection'
+    bl64_os_cp_file "$DEVAP_DOCS/contributing/COPYING" "$DEVAP_COLLECTIONS/${collection}/COPYING"
+    bl64_os_cp_file "$DEVAP_DOCS/collections/${collection}.md" "$DEVAP_COLLECTIONS/${collection}/README.md"
   done
 
 }
@@ -107,9 +130,10 @@ function devap_build_check() {
 function devap_build_help() {
 
   bl64_msg_show_usage \
-    '<-t|-p|u> [-c collection] [-h]' \
+    '<-r|-t|-p|-uu> [-c collection] [-h]' \
     'Build ansible galaxy packages' \
     '
+  -r           : refresh collection doc from master
   -t           : build testing packages
   -p           : build production packages
   -u           : publish production packages (needs Galaxy token set in DEVAP_SECRET_GALAXY_TOKEN)
@@ -130,8 +154,12 @@ declare devap_build_option=''
 declare devap_build_collection=''
 
 (($# == 0)) && devap_build_help && exit 1
-while getopts ':tpuc:h' devap_build_option; do
+while getopts ':rtpuc:h' devap_build_option; do
   case "$devap_build_option" in
+  r)
+    devap_build_command='devap_build_refresh'
+    devap_build_command_tag='refresh collection doc'
+    ;;
   t)
     devap_build_command='devap_build_test'
     devap_build_command_tag='testing package build'
@@ -172,7 +200,7 @@ fi
 
 bl64_msg_show_batch_start "$devap_build_command_tag"
 case "$devap_build_command" in
-'devap_build_test' | 'devap_build_prod' | 'devap_build_publish') "$devap_build_command" "$devap_build_collection" ;;
+'devap_build_test' | 'devap_build_prod' | 'devap_build_publish' | 'devap_build_refresh') "$devap_build_command" "$devap_build_collection" ;;
 esac
 devap_build_status=$?
 
